version: 1.0.{build}
environment:
  nodejs_version: "4.2.2"
  GITHUB_KEY:
    secure: eZcSozzDKzRJhSoXL7LS9w1jqFLdkiRT4H57JoWGpKj/kS6NC/DP3ColwKkvSeFn
  NUCLEUS_CERT_PASS:
    secure: UEVPxVtsn5UnAi3PhhkUSA==

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm upgrade

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

build_script:
- cmd: npm run make:win
- cmd: npm run release:win

artifacts:
  - path: 'dist\build\installer32\Nucleus PlayerSetup.exe'
  - path: 'dist\build\installer64\Nucleus PlayerSetup.exe'
